AWS_ACCESS_KEY_ID = ''
AWS_SECRET_ACCESS_KEY = ''
AWS_KEY_PAIR_NAME = ''
AWS_BUCKET = ''

AWS_INSTANCE_TYPE = 'c1.medium'
AWS_MAX_INSTANCES=30
AWS_PRICE_PER_HOUR=.025 #you are responsible for these charges
